import { Product } from '../../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-apple-1',
    name: 'Fresh Apples Gala',
    description: 'Crisp and sweet Gala apples perfect for snacking.',
    price: '180',
    discountPrice: '150',
    images: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce'],
    category: { id: 'cat-fruit', name: 'Fruits' },
    stockQuantity: 120,
    weight: 1,
    unit: 'KG',
    isFeatured: true,
    averageRating: 4.6,
    totalReviews: 214,
    variants: [
      {
        id: 'var-apple-500g',
        productId: 'prod-apple-1',
        sku: 'APL-G-500',
        name: 'Gala 500g',
        attributes: { weight: '500g' },
        price: '90',
        discountPrice: '80',
        stockQuantity: 80,
        lowStockThreshold: 10,
        isActive: true,
        sortOrder: 1,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'var-apple-1kg',
        productId: 'prod-apple-1',
        sku: 'APL-G-1K',
        name: 'Gala 1kg',
        attributes: { weight: '1kg' },
        price: '180',
        discountPrice: '150',
        stockQuantity: 40,
        lowStockThreshold: 8,
        isActive: true,
        sortOrder: 2,
        createdAt: '',
        updatedAt: '',
      },
    ],
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-banana-1',
    name: 'Banana Yellaki',
    description: 'Sweet Yellaki bananas rich in potassium and fiber.',
    price: '60',
    images: ['https://images.unsplash.com/photo-1571772996211-2f02c9727629'],
    category: { id: 'cat-fruit', name: 'Fruits' },
    stockQuantity: 200,
    weight: 1,
    unit: 'KG',
    isFeatured: false,
    averageRating: 4.4,
    totalReviews: 132,
    variants: [
      {
        id: 'var-banana-500g',
        productId: 'prod-banana-1',
        sku: 'BAN-Y-500',
        name: '500g Bunch',
        attributes: { weight: '500g' },
        price: '35',
        stockQuantity: 100,
        lowStockThreshold: 12,
        isActive: true,
        sortOrder: 1,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'var-banana-1kg',
        productId: 'prod-banana-1',
        sku: 'BAN-Y-1K',
        name: '1kg Bunch',
        attributes: { weight: '1kg' },
        price: '60',
        stockQuantity: 100,
        lowStockThreshold: 12,
        isActive: true,
        sortOrder: 2,
        createdAt: '',
        updatedAt: '',
      },
    ],
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-milk-1',
    name: 'Organic Cow Milk',
    description: 'Farm-fresh organic cow milk, homogenized and pasteurized.',
    price: '70',
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b'],
    category: { id: 'cat-dairy', name: 'Dairy' },
    stockQuantity: 60,
    unit: 'LITRE',
    isFeatured: true,
    averageRating: 4.7,
    totalReviews: 98,
    variants: [
      {
        id: 'var-milk-500ml',
        productId: 'prod-milk-1',
        sku: 'MLK-O-500',
        name: '500 ml Pack',
        attributes: { volume: '500ml' },
        price: '40',
        stockQuantity: 30,
        lowStockThreshold: 6,
        isActive: true,
        sortOrder: 1,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'var-milk-1l',
        productId: 'prod-milk-1',
        sku: 'MLK-O-1L',
        name: '1 Litre Pack',
        attributes: { volume: '1L' },
        price: '70',
        discountPrice: '65',
        stockQuantity: 30,
        lowStockThreshold: 6,
        isActive: true,
        sortOrder: 2,
        createdAt: '',
        updatedAt: '',
      },
    ],
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-curd-1',
    name: 'Probiotic Curd',
    description: 'Thick and creamy probiotic curd perfect for daily meals.',
    price: '55',
    discountPrice: '50',
    images: ['https://images.unsplash.com/photo-1562967914-608f82629710'],
    category: { id: 'cat-dairy', name: 'Dairy' },
    stockQuantity: 80,
    unit: 'BOX',
    isFeatured: false,
    averageRating: 4.2,
    totalReviews: 64,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-cheese-1',
    name: 'Cheddar Cheese Block',
    description: 'Matured cheddar cheese block, great for sandwiches and cooking.',
    price: '320',
    images: ['https://images.unsplash.com/photo-1506806732259-39c2d0268443'],
    category: { id: 'cat-dairy', name: 'Dairy' },
    stockQuantity: 35,
    weight: 0.5,
    unit: 'KG',
    isFeatured: true,
    averageRating: 4.5,
    totalReviews: 77,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-tomato-1',
    name: 'Tomato (Hybrid)',
    description: 'Juicy hybrid tomatoes ideal for salads and cooking.',
    price: '50',
    images: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=compress'],
    category: { id: 'cat-vegetable', name: 'Vegetables' },
    stockQuantity: 150,
    weight: 1,
    unit: 'KG',
    isFeatured: false,
    averageRating: 4.1,
    totalReviews: 145,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-potato-1',
    name: 'Potato (Local)',
    description: 'Starchy potatoes perfect for curries, fries, and baking.',
    price: '40',
    images: ['https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=compress'],
    category: { id: 'cat-vegetable', name: 'Vegetables' },
    stockQuantity: 220,
    weight: 1,
    unit: 'KG',
    isFeatured: false,
    averageRating: 4.0,
    totalReviews: 112,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-lettuce-1',
    name: 'Romaine Lettuce',
    description: 'Crisp romaine lettuce heads great for salads and wraps.',
    price: '90',
    images: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6'],
    category: { id: 'cat-vegetable', name: 'Vegetables' },
    stockQuantity: 45,
    unit: 'PIECE',
    isFeatured: true,
    averageRating: 4.3,
    totalReviews: 56,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-almond-1',
    name: 'Roasted Almonds',
    description: 'Lightly salted roasted almonds for a healthy snack.',
    price: '450',
    discountPrice: '399',
    images: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836'],
    category: { id: 'cat-snacks', name: 'Snacks' },
    stockQuantity: 70,
    weight: 0.5,
    unit: 'KG',
    isFeatured: true,
    averageRating: 4.8,
    totalReviews: 188,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-chips-1',
    name: 'Multigrain Chips',
    description: 'Baked multigrain chips with a spicy peri-peri seasoning.',
    price: '120',
    images: ['https://images.unsplash.com/photo-1585238341986-37b1f504e562'],
    category: { id: 'cat-snacks', name: 'Snacks' },
    stockQuantity: 160,
    unit: 'BOX',
    isFeatured: false,
    averageRating: 4.0,
    totalReviews: 93,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-granola-1',
    name: 'Honey Nut Granola',
    description: 'Crunchy granola mix with nuts, seeds, and a hint of honey.',
    price: '260',
    discountPrice: '230',
    images: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=compress'],
    category: { id: 'cat-snacks', name: 'Snacks' },
    stockQuantity: 90,
    unit: 'BOX',
    isFeatured: false,
    averageRating: 4.4,
    totalReviews: 120,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-berries-1',
    name: 'Blueberries Pack',
    description: 'Sweet and tangy blueberries packed with antioxidants.',
    price: '320',
    images: ['https://images.unsplash.com/photo-1502741338009-cac2772e18bc'],
    category: { id: 'cat-fruit', name: 'Fruits' },
    stockQuantity: 55,
    unit: 'BOX',
    isFeatured: true,
    averageRating: 4.9,
    totalReviews: 140,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-yogurt-1',
    name: 'Greek Yogurt (Plain)',
    description: 'High-protein plain Greek yogurt, thick and creamy.',
    price: '180',
    images: ['https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43'],
    category: { id: 'cat-dairy', name: 'Dairy' },
    stockQuantity: 65,
    unit: 'BOX',
    isFeatured: false,
    averageRating: 4.5,
    totalReviews: 88,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-bread-1',
    name: 'Whole Wheat Bread',
    description: 'Soft and healthy whole wheat bread loaf.',
    price: '55',
    images: ['https://images.unsplash.com/photo-1608198093002-ad4e005484ec'],
    category: { id: 'cat-bakery', name: 'Bakery' },
    stockQuantity: 110,
    unit: 'PIECE',
    isFeatured: false,
    averageRating: 4.1,
    totalReviews: 76,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-eggs-1',
    name: 'Free Range Eggs (12)',
    description: 'Protein-rich free range eggs sourced from local farms.',
    price: '110',
    discountPrice: '99',
    images: ['https://images.unsplash.com/photo-1517959105821-eaf2591984c2'],
    category: { id: 'cat-dairy', name: 'Dairy' },
    stockQuantity: 140,
    unit: 'BOX',
    isFeatured: true,
    averageRating: 4.6,
    totalReviews: 167,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-orange-1',
    name: 'Mandarin Oranges',
    description: 'Juicy mandarins packed with vitamin C.',
    price: '140',
    images: ['https://images.unsplash.com/photo-1505253758473-96b7015fcd40'],
    category: { id: 'cat-fruit', name: 'Fruits' },
    stockQuantity: 95,
    weight: 1,
    unit: 'KG',
    isFeatured: false,
    averageRating: 4.3,
    totalReviews: 101,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'prod-spinach-1',
    name: 'Baby Spinach',
    description: 'Tender baby spinach leaves, triple-washed and ready to cook.',
    price: '70',
    images: ['https://images.unsplash.com/photo-1506807803488-8eafc15323c1'],
    category: { id: 'cat-vegetable', name: 'Vegetables' },
    stockQuantity: 85,
    unit: 'BOX',
    isFeatured: true,
    averageRating: 4.7,
    totalReviews: 118,
    createdAt: '',
    updatedAt: '',
  },
];
